# your informations
author:
  name: Bernardo Pacheco
  description: JavaScript software engineer
  picture: //avatars1.githubusercontent.com/u/5872815?v=2&s=460

# site description
description: site description

# site url
url: http://bernardopacheco.net

# your github username
github_username: bernardopacheco

# set true to include or false to exclude share option
share:
  twitter: true
  facebook: true
  google_plus: true
  linkedin: true
  disqus: true

# if share.facebook is true, provide your facebook app id
facebook_app_id: 730635297031262

# if share.disqus is true, provide your disqus shortname
disqus_username: bernardopacheco

markdown: kramdown
exclude: [ 'README.md', 'src/', 'node_modules', 'bower_components', 'package.json', 'bower.json', 'Gruntfile.js' ]
